<?php

namespace AppBundle\Repository;

/**
 * PersonneRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PersonneRepository extends \Doctrine\ORM\EntityRepository
{

    private function getPersonnesByIntervalQuery($min,$max) {
        $qb = $this->createQueryBuilder('p');
        $query = $qb->where('p.age >= :min and p.age<= :max')
            ->setParameters(array(
                'min'=>$min,
                'max'=>$max,
            ));
        return $query;
    }

    public function getPersonnesByAgeInterval($min,$max) {

        $query = $this->getPersonnesByIntervalQuery($min,$max)
                      ->getQuery();
        return $query->getResult();
    }

    public function getOrdredPersonneByAgeIntervalAndName($min,$max,$name){
        $query = $this->getPersonnesByIntervalQuery($min,$max)
                      ->andWhere('p.name like %:name%')
                      ->orderBy('p.age','ASC')
                      ->setParameters(array(
                          'name'=>$name
                      ))
                      ->getQuery();
        return $query->getResult();
    }

}
