tekup_third:
    resource: "@TekupThirdBundle/Resources/config/routing.yml"
    prefix:   /third

tekup_first:
    resource: "@TekupFirstBundle/Resources/config/routing.yml"
    prefix:   /first

app:
    resource: '@AppBundle/Controller/'
    type: annotation
